### ISSUE TITLE
32 vulnerabilities and breaking angular 7 project 

### ISSUE THREAD

**Issue by phil123456** [basst314/ngx-webcam#52]
everything in the title

**Comment by basst314** [comment]
Hi @phil123456
Can you give some more details about the issues you‘re experiencing?
Thanks

**Comment by phil123456** [comment]
something weird

I install the package, then it complains about 32 vulnerabilities
I do an audit fix, there are like 21 vulnerabilities remaining then not possible to start the application anymore

some weird error :

`Data path ".builders['app-shell']" should have required property 'class'.`

the only solution was to recreate the angular project with angular CLI

yet even doing so, I have 3 unsolved vulnerabilities, someone made crapy updates I guess

regards

**Comment by phil123456** [comment]
I made a new project from scratch

```
ng new webcam-test
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? SASS   [ http://sass-lang.com   ]
...
found 3 vulnerabilities (2 low, 1 high)
...
npm audit fix
2 package updates for 2 vulns involved breaking changes

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\@angular-devkit\core\src\workspace\worksp
ace.js:215:42)
    at MergeMapSubscriber._tryNext (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MapSubscriber._next (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (Z:\WORK\ELECTRONICS\PartsManager\webcam-test\node_modules\rxjs\internal\operators\switchMap.js:86:26)
```

I sugest not doing the audit fix, it works that way

**Comment by basst314** [comment]
But the vulnerabilities show up before you even add the ngx-webcam lib, right?

**Comment by basst314** [comment]
What angular versions are you using?

**Comment by phil123456** [comment]
yep it appears to be an angular problem , not ngx-webcam, I could make everything work fine
```

{
  "name": "parts-manager",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "core-js": "^2.5.4",
    "ngx-webcam": "^0.2.5",
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.0",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}

```

**Comment by basst314** [comment]
Okay, thanks. I will resolve this issue then.
